apiVersion: v1
version: 3.11.0
appVersion: 1.0.0
description: Deploys a DISC app
name: disc-generic
home: https://github.com/OU-DISC/helmcharts
maintainers:
  - name: Wolfgang Jentner
    email: wjentner@ou.edu
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: added app.pvc.readOnly as an optional argument
    - kind: added
      description: added app.hostVolumes[*].readOnly as an optional argument
    - kind: added
      description: added app.pvc.selector as an optional argument
    - kind: added
      description: added app.extraPvcs
    - kind: fixed
      description: Updated documentation
