{{- if .Values.app.configMaps }}
{{- range .Values.app.configMaps }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "dbvis.labels" $ | nindent 4 }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
data:
{{- range $filename, $filecontent := .data }}
  {{ $filename }}: |-
{{ tpl $filecontent $ | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
