{{- if .Values.app.secrets }}
{{- range .Values.app.secrets }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "dbvis.labels" $ | nindent 4 }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
{{- if .stringData }}
stringData:
{{- range $filename, $filecontent := .stringData }}
  {{ $filename }}: |-
{{ tpl $filecontent $ | indent 4 }}
{{- end }}
{{- end }}
{{- if .data }}
data:
{{- range $filename, $filecontent := .data }}
  {{ $filename }}: |-
{{ tpl $filecontent $ | indent 4 }}
{{- end }}
{{- end }}
type: {{ .type | default "Opaque" }}
{{- end }}
{{- end }}

